services:
  influxdb:
    image: influxdb:1.8.2
    container_name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_NAME}
    ports:
      - ${COMPOSE_PROJECT_PORT}:8086
    environment:
      - INFLUXDB_DB=k6
    networks:
      net: {}

networks:
  net:
    external: true
    name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_CNET}