services:
  influxdb:
    image: influxdb:1.8.2
    container_name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_NAME}
    ports:
      - ${COMPOSE_PROJECT_PORT}:8086
    environment:
      - INFLUXDB_DB=k6
