[program:java-dev]
# Added --server.address=0.0.0.0 just in case Docker blocks localhost port forwarding!
directory=/var/www
command=mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=5000 --server.address=0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0