services:

  grafana:
    image: grafana/grafana:8.1.2
    container_name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_NAME}
    ports:
      - ${COMPOSE_PROJECT_PORT}:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config:/etc/grafana/provisioning/
    networks:
      - itx-pr-network

networks:
  itx-pr-network:
    external: true
